services:

  threat-map-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: threat-map-api
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8090:8090"
    environment:
      ABUSEIPDB_KEY: ${ABUSEIPDB_KEY}
      GREYNOISE_KEY: ${GREYNOISE_KEY}
      CENSYS_API_TOKEN: ${CENSYS_API_TOKEN}
      CORS_ORIGINS: '["http://localhost:3001","https://threat.yohanesfc.web.id"]'
    networks:
      - threat-map-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8090/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  threat-map-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://threat.yohanesfc.web.id
        NEXT_PUBLIC_WS_URL: wss://threat.yohanesfc.web.id
    container_name: threat-map-frontend
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: https://threat.yohanesfc.web.id
      NEXT_PUBLIC_WS_URL: wss://threat.yohanesfc.web.id
    networks:
      - threat-map-net
    depends_on:
      - threat-map-api

networks:
  threat-map-net:
    driver: bridge
